menu:
    カテゴリー: /category/
    タグ: /tag/
    月別: /archive/
    サイトについて: /about/
    RSS: /atom.xml


widgets:
  - category
  - tagcloud
  - archive
  - link


category:
  name: カテゴリー

tagcloud:
  name: タグクラウド

archive:
  name: 月別

recent_posts:
  name: 最近の投稿
  amount: 5

link:
  name: リンク
  list:
    サイトについて: /about/
    RSS: /atom.xml

search:
  name: 検索
